### ISSUE TITLE
Missing setup.sh file

### ISSUE THREAD

**Issue by ameirshaa** [CERNatschool/frame-viewer#1]
There are one or more missing files for this folder.

**Comment by twhyntie** [comment]
Hi @ameirshaa 
Thanks for this - indeed not all of the files were committed when I last edited them, apologies!
I will create a pull request and add them now.
Thanks for pointing this out, @twhyntie

**Comment by twhyntie** [comment]
Fixed by Pull Request #2 - thanks again @ameirshaa for pointing this out :smile:
